apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: panos-cluster
  namespace: panos
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
      - name: plain
        port: 9096
        tls: false
        type: internal
      - name: tls
        port: 9094
        tls: true
        type: internal
    replicas: 1
    storage:
      class: longhorn
      deleteClaim: false
      size: 1Gi
      type: persistent-claim
    version: 3.4.0
  zookeeper:
    replicas: 1
    storage:
      class: longhorn
      deleteClaim: false
      size: 1Gi
      type: persistent-claim
